spring:
  application:
    name: ddl
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./db/nnmhl-server
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: target/sql/ddl.sql
